name: airflow
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - production_net

  airflow-webserver:
    image: apache/airflow:2.9.3-python3.11
    container_name: airflow-webserver
    entrypoint: /bin/bash
    command: >
      -c "exec airflow webserver"
    ports:
      - "8081:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=wmSpjmCJ477jqpJE9BlzuzzI_Cw4P4RRGBZj1KeAPcU=
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/postgres
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=some-secret
      - LABEL_STUDIO_URL=http://label-studio:8080
      - LABEL_STUDIO_USER_TOKEN=ab9927067c51ff279d340d7321e4890dc2841c4a
      - MINIO_URL=http://minio:9000
      - MINIO_USER=your-access-key
      - MINIO_PASSWORD=your-secret-key
    volumes:
      - /home/cc/eval-loop-chi/dags:/opt/airflow/dags
      - airflow_shared:/opt/airflow
    depends_on:
      airflow-setup:
        condition: service_completed_successfully
    networks:
      - production_net

  airflow-scheduler:
    image: apache/airflow:2.9.3-python3.11
    container_name: airflow-scheduler
    entrypoint: /bin/bash
    command: >
      -c "exec airflow scheduler"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=wmSpjmCJ477jqpJE9BlzuzzI_Cw4P4RRGBZj1KeAPcU=
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - LABEL_STUDIO_URL=http://label-studio:8080
      - LABEL_STUDIO_USER_TOKEN=ab9927067c51ff279d340d7321e4890dc2841c4a
      - MINIO_URL=http://minio:9000
      - MINIO_USER=your-access-key
      - MINIO_PASSWORD=your-secret-key
    volumes:
      - /home/cc/eval-loop-chi/dags:/opt/airflow/dags
      - airflow_shared:/opt/airflow
    depends_on:
      airflow-setup:
        condition: service_completed_successfully
    networks:
      - production_net

  airflow-setup:
    image: apache/airflow:2.9.3-python3.11
    container_name: airflow-setup
    entrypoint: /bin/bash
    command: >
      -c "airflow db migrate && airflow users create --username admin --firstname Airflow --lastname Admin --role Admin --email airflow@example.com --password airflow"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=wmSpjmCJ477jqpJE9BlzuzzI_Cw4P4RRGBZj1KeAPcU=
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - /home/cc/eval-loop-chi/dags:/opt/airflow/dags
      - airflow_shared:/opt/airflow
    networks:
      - production_net
    restart: "no"

volumes:
  airflow_shared:
  postgres_data:

networks:
  production_net:
    external: true
